### PR TITLE
Update tool_destinations.yaml

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@bernt-matthias is 12GB enough for Mitos2?

**Comment by bernt-matthias** [comment]
@bgruening for typical metazoan mitogenomes this should be sufficient. For larger (plant and fungal) MITOS2 might need more, but then jobs are resubmitted with more memory anyway, or?

**Comment by bgruening** [comment]
Yes, but I see *a lot* of Mitos2 jobs are being resubmitted, so I give it more from the beginning.

**Comment by bgruening** [comment]
For your stats @bernt-matthias 

tool runs: 
```
 toolshed.g2.bx.psu.edu/repos/iuc/mitos2/mitos2/2.0.6                  |    6710
```

**Comment by bernt-matthias** [comment]
Thanks @bgruening .. good to know that MITOS2 gets accepted on usegalaxy.eu. The main mitos2 webserver is still processed 2527 jobs last month .. Guess I need to enforce this transition a bit (with tutorials?) since our service will probably go down in the mid term...

**Comment by bgruening** [comment]
The tutorial is always nice, but also time-consuming for you I assume. Maybe move the link to the top and make it a bigger button?

**Comment by bernt-matthias** [comment]
> The tutorial is always nice, but also time-consuming for you I assume. 

Thinking of a screencast video which should not take to much time...

**Pull request merged**
