### PR TITLE
alphafold: request 32GB RAM

### PR DESCRIPTION
**Pull request by martenson**
per one of the authors this should help resolving the `RuntimeError: HHblits failed`

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by gmauro** [comment]
No! It will never run. Our GPU nodes have maximum 16GB of RAM

**Comment by bgruening** [comment]
:(

**Comment by martenson** [comment]
Oh okay, for some reason I thought GPUs are very limited, that is good news then. Thank you very much for your efforts.

**Comment by gmauro** [comment]
@martenson @bgruening alphafold is now running on CPU, 10 cores and 32 GB of RAM

**Pull request merged**
