### PR TITLE
run deeptools in Singularity

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by kysrpex** [comment]
Before I click approve too fast: how is the tool wrapper version matched to a singularity container on CVMFS?

I am asking because I see more specific version numbers for the tool wrapper (e.g. "2.5.1.1.0") than those for the containers available in CVMFS (e.g. /cvmfs/singularity.galaxyproject.org/d/e/deeptools:2.5.1--py36_0). I need to be sure that a matching container will be found before I hit approve.

I can investigate this further but if you know the answer then I could approve faster.

**Comment by mira-miracoli** [comment]
we could test this in a test instance maybe?

**Comment by bgruening** [comment]
Look in the gui at the admin account under tool dependencies. Which container is used. Short answer is that it depends if deeptoolsnhas only one dependency or multiple defined.
I think it works.since this setting was applied over the weekend and tested at least for the latest deeptolls version

**Comment by bgruening** [comment]
And while I write this I remember that this PR will NOT work. I needed to.give the exact same tool.ID here as in the shared tpv.

**Comment by bgruening** [comment]
I don't know why the shared definition was preferred over this addition here. But I needed to change the key to match the one in the shared DB :-(

**Comment by mira-miracoli** [comment]
another thought - we have singularity enabled on pulsar – if it runs there, it should run in our cluster, too, right?

**Comment by kysrpex** [comment]
> I don't know why the shared definition was preferred over this addition here. But I needed to change the key to match the one in the shared DB :-(

Strange, at least with the dry run it works properly.

**no entry in tools.yml**
```shell
(.venv) $ tpv dry-run --job-conf job_conf.yml --tool toolshed.g2.bx.psu.edu/repos/bgruening/deeptools/deeptools_bamCompare/.*
!!python/object:galaxy.jobs.JobDestination
converted: false
env:
- {name: GALAXY_MEMORY_MB, value: '12288'}
id: condor_tpv
legacy: false
params: {description: deeptools_bamCompare, docker_memory: 12G, metadata_strategy: extended,
  request_cpus: '10', request_memory: 12G, submit_request_gpus: '0', tmp_dir: true}
resubmit: []
runner: condor
shell: null
tags: null
url: null
```

**entry in tools.yml**
```yaml
  toolshed.g2.bx.psu.edu/repos/bgruening/deeptools/.*:
    scheduling:
      require:
        - singularity    
```
```shell
(.venv) $ tpv dry-run --job-conf job_conf.yml --tool toolshed.g2.bx.psu.edu/repos/bgruening/deeptools/deeptools_bamCompare/.*
!!python/object:galaxy.jobs.JobDestination
converted: false
env:
- {name: GALAXY_MEMORY_MB, value: '3891'}
id: condor_singularity
legacy: false
params: {description: deeptools_bamCompare, docker_memory: 3.8G, metadata_strategy: extended,
  request_cpus: '1', request_memory: 3.8G, singularity_default_container_id: /cvmfs/singularity.galaxyproject.org/all/centos:8.3.2011,
  singularity_enabled: true, singularity_volumes: '$_CONDOR_SCRATCH_DIR:rw,$job_directory:rw,$tool_directory:ro,$job_directory/outputs:rw,$working_directory:rw,/data/db/:ro,/data/dnb01/galaxy_db/:ro,/data/dnb02/galaxy_db/:ro,/data/dnb03/galaxy_db/:ro,/data/dnb05/galaxy_db/:ro,/data/dnb06/galaxy_db/:rw,/data/dnb07/galaxy_db/:rw,/data/dnb08/galaxy_db/:rw,/data/dp01/galaxy_db/:rw,/data/0/galaxy_db/:ro,/data/1/galaxy_db/:ro,/data/2/galaxy_db/:ro,/data/3/galaxy_db/:ro,/data/4/galaxy_db/:ro,/data/5/galaxy_import/galaxy_user_data/:ro,/data/6/galaxy_db/:ro,/data/7/galaxy_db/:ro,/usr/local/tools/:ro',
  submit_request_cpus: '1', submit_request_gpus: '0', submit_request_memory: 3.8G,
  tmp_dir: true}
resubmit: []
runner: condor
shell: null
tags: null
url: null

> But I needed to change the key to match the one in the shared DB :-(

Is this still in production? Maybe I can have a look after lunch

**Comment by bgruening** [comment]
depends if there was a restart ... This change had no effect in my test, but also did not break anything. Please merge and then we can see. I know need to leave the bus and will not be online anymore. Please proceed with whatever you think is best.

**Comment by kysrpex** [comment]
Since you said that at least the latest version works (so we would not be causing a total blackout) and I do not have the means at the moment not to be testing in production, let's proceed like this: I run Ephemeris once, I merge this PR, run Jenkins, run Ephemeris and compare the results to see if everything went well.

**Review by kysrpex — APPROVED** [review]

**Comment by kysrpex** [comment]
I changed my mind: let's take the risk and run tool tests directly with Singularity enabled.

**Pull request merged**
