### PR TITLE
add TMP, TEMP and TMPDIR to hcmr destination

### PR DESCRIPTION
**Pull request by mtangaro**
Fix for "Fatal error: cannot create 'R_TempDir'"

### CODE REVIEW

**Review by sanjaysrikakulam — APPROVED** [review]

**Comment by bgruening** [comment]
@mtangaro which tool has emitted that? We might need to fix the tool or increase the profile version of the tool.Amanda

**Comment by mtangaro** [comment]
> @mtangaro which tool has emitted that? We might need to fix the tool or increase the profile version of the tool.Amanda

It's "OBIS occurences": https://toolshed.g2.bx.psu.edu/repository?repository_id=cd90b8e977b0c4bc

**Comment by bgruening** [comment]
Mh, interesting it has profile="20.01"

https://github.com/galaxyproject/galaxy/pull/16594/files

So we should add a comment and remove this at some point again. Have you tested this with 24.0?

**Comment by mtangaro** [comment]
> Mh, interesting it has profile="20.01"
> 
> https://github.com/galaxyproject/galaxy/pull/16594/files
> 
> So we should add a comment and remove this at some point again. Have you tested this with 24.0?

It works fine on EU with default destination.

**Pull request merged**
