### PR TITLE
Remove obsolete vars file 'central_manager.yml' from 'group_vars/'

### PR DESCRIPTION
**Pull request by sj213**
Just a small "cosmetic" PR: Looking at the vars files I found a file "central_manager.yml" that contains ancient config settings. The config data in this unused file has been obsolete for years now (last update Aug 2019, and I think it was meant for the stillborn NEMO/ROCED compute cluster), so the file can probably go.

### CODE REVIEW

**Comment by gmauro** [comment]
Thank you @sj213 
Could you remove https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/central-manager.yml as well?
That was the previous central manager

**Comment by sj213** [comment]
Ah, ok, overlooked the host definition file (now both files should be deleted by the PR) [I'm a bit late but I was in a marathon-VC until a few minutes ago...]

**Comment by gmauro** [comment]
Thank you.

**Comment by bgruening** [comment]
Thanks @sj213 ... please more of those :)

**Pull request merged**
