### PR TITLE
circos: Run in Singularity

### PR DESCRIPTION
**Pull request by kysrpex**
Run the circos tool on Singularity destinations.

### CODE REVIEW

**Review by mira-miracoli — APPROVED** [review]
Looks good to me, thank you!

**Comment by kysrpex** [comment]
Let's respect read-only Friday? Or merge and run Jenkins immediately?

**Comment by mira-miracoli** [comment]
I think this change is has so little complexity, that it can be even merged on Friday :)

**Comment by hexylena** [comment]
let me know when it's live and I should re-test (or is it immediate?)

**Comment by kysrpex** [comment]
> let me know when it's live and I should re-test (or is it immediate?)

Jenkins runs every day at 00:31 at it typically takes between 10 and 30 minutes to run the playbook.

**Comment by kysrpex** [comment]
But we are running it for you right now :)

**Comment by hexylena** [comment]
>Jenkins runs every day at 00:31

ah that's re-enabled? oh good :) glad y'all could get jenkins working again

> But we are running it for you right now :)

fantastic! I'll begin testing directly then.

**Pull request merged**
