### PR TITLE
Try to add ecology subdomains here

### PR DESCRIPTION
**Pull request by yvanlebras**
And please don't be cruel if this is totally wrong, I'm just an ecolog ;)

### CODE REVIEW

**Comment by bgruening** [comment]
Looks in general good. The categories needs to be defined here: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/config/tool_conf.xml

**Comment by bgruening** [comment]
I will merge and it will be deployed at midnight, then please check what is missing and we add this gradually.

**Comment by yvanlebras** [comment]
ok, It appears that there is lacking:

**Comment by bgruening** [comment]
Ok, that should be hopefully fixed tomorrow.

**Pull request merged**
