### PR TITLE
change usegalaxy-eu.htcondor name, use underscore

### PR DESCRIPTION
**Pull request by bgruening**
This should hopefully fix https://build.galaxyproject.eu/job/usegalaxy-eu/job/playbooks/job/sn05/684/console

### CODE REVIEW

**Comment by bgruening** [comment]
Any comments @mira-miracoli @sanjaysrikakulam?

**Comment by mira-miracoli** [comment]
I get "Access Denied" on the link, despite being logged in

**Comment by mira-miracoli** [comment]
In the [requirements.yaml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/680e82b466e2cb1f3204a7dc31ba8b25bae2b61a/requirements.yaml#L84) it is written with underscore:
`  - name: usegalaxy_eu.htcondor`

**Review by mira-miracoli — APPROVED** [review]

**Comment by bgruening** [comment]
https://github.com/usegalaxy-eu/infrastructure-playbook/commit/fbfa168ed121c430c1e42aa2b495a9b220c7890d jupp, just not sure when all of those dashes changed to underscore.

**Pull request merged**
