### PR TITLE
EIRENE subdomain changes

### PR DESCRIPTION
**Pull request by hechth**

### CODE REVIEW

**Comment by mira-miracoli** [comment]
Hi, please add a folder named like your subdomain, with a subfolder called themes containing a yaml file named like your subdomain (if you are not using a theme yet, you can leave the file empty).
~~~
└── subdomains/
    ├── ...
    └── eirene/
        └── themes/
            └── eirene.yml
~~~
https://github.com/usegalaxy-eu/infrastructure-playbook/tree/master/files/galaxy/subdomains

**Comment by hechth** [comment]
@mira-miracoli I added the yml file - is there anything else that needs to be done now?

**Comment by bgruening** [comment]
@hechth can you ping me whan you take all these PRs out of draft?

**Comment by bgruening** [comment]
Upps, sorry.

**Review by mira-miracoli — APPROVED** [review]
looks good to me, I think you can set it as ready and we merge it

**Pull request merged**
