### PR TITLE
add copernicus notebook

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@Marie59 ping

**Comment by Marie59** [comment]
ooh right I always forget

**Comment by bgruening** [comment]
If this gets merged, the next day the tool should be working.

**Comment by Marie59** [comment]
I don't understand the error. Why is searching for a login ?

**Comment by bgruening** [comment]
Its doing some live testing of the rules and ITs do require a Galaxy login I think.

Don't worry, admins told me that is ok :)

**Comment by kysrpex** [comment]
> TPV is new'ish yes. And its a bit redundant, we could be smarter here, but for the time being, we need to do that.
> 
> @kysrpex we could use wildcards here for all interactive_tools_* ?

Yes, for example u can add an entry `interactive_tool_*:` under [line 18](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/2cf6723e6871e60a727487bed98c7c7dc22c6bf0/files/galaxy/tpv/interactive_tools.yml#L18) and make it inherit from `interactive_tool`. Alternatively just rename [`interactive_tool`](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/2cf6723e6871e60a727487bed98c7c7dc22c6bf0/files/galaxy/tpv/interactive_tools.yml#L3).

**Pull request merged**
