### PR TITLE
Add conf for gxit rstudio_askor

### PR DESCRIPTION
**Pull request by abretaud**
Just the tool config stuff for https://github.com/usegalaxy-eu/galaxy/pull/250

### CODE REVIEW

**Comment by abretaud** [comment]
Hey! I don't see this gxit on usegalaxy.eu, did I forget to change something in the conf?

**Comment by bgruening** [comment]
Oh fu** realy? Sorry, I will have a look.

**Comment by bgruening** [comment]
Ah, singlecell only https://singlecell.usegalaxy.eu/root?tool_id=interactive_tool_rstudio_askor

Fix is coming.

**Comment by bgruening** [comment]
Fixed in the last commit. Do you need it today? If not it will be also on the main EU side, tomorrow.

**Comment by bgruening** [comment]
Btw. this link should work:  https://usegalaxy.eu/root?tool_id=interactive_tool_rstudio_askor

**Comment by abretaud** [comment]
Thanks! good catch, I hadn't seen the single-cell in the section ;)
No hurry, tomorrow is fine

I get this error ATM, but maybe it will go away tomorrow?

image

**Pull request merged**
