### PR TITLE
Bump ansible

### PR DESCRIPTION
**Pull request by mira-miracoli**
- BUMP ansible-core from 2.11.3 → 2.14.5 (2021 → now)
- DELETE dj-wasabi.telegraf role, pull latest role from requirements.yml

### CODE REVIEW

**Review by sanjaysrikakulam — APPROVED** [review]
Let's try!

**Comment by mira-miracoli** [comment]
I will curate a list of Jenkins projects and errors, give me a second

**Review by kysrpex — APPROVED** [review]
Let's do it! I suggest not to run all projects at once so we just break one thing at a time if things go bad.

**Comment by mira-miracoli** [comment]
Ansible should never break anything, the playbooks might just fail

**Comment by mira-miracoli** [comment]
We need to change python in all projects in Jenkins to 3.9

**Pull request merged**
