### PR TITLE
Add fairease subdomain

### PR DESCRIPTION
**Pull request by Marie59**
Creation of a fairease.usegalaxy should be use for the Fair-Ease project. Maybe when we have all the stable tools on it afterwards we can create a subdomain with a more meaningfull/general name @yvanlebras.

### CODE REVIEW

**Comment by Marie59** [comment]
If I want to remove some of the tools and keep only basics one, ecology and climat ones should I do it on this PR by editing "global_host_filters.py.j2" ? @yvanlebras and @bgruening

**Comment by bgruening** [comment]
You can not hide single tools only categories atm and yes you would need to do this global_host_filters.py.j2

**Comment by yvanlebras** [comment]
yes (if I am not wrong ;) )

**Comment by bgruening** [comment]
@Marie59 @yvanlebras please lets agree on one domain name. Its hard to remove domains after the fact.

**Comment by Marie59** [comment]
> You can not hide single tools only categories atm and yes you would need to do this global_host_filters.py.j2

Thanks for the quick reply ! what does categories atm means ?

**Comment by Marie59** [comment]
> @Marie59 @yvanlebras please lets agree on one domain name. Its hard to remove domains after the fact.

Then I think it's gonna stay fairease. What do you think Yvan ?

**Comment by bgruening** [comment]
Are you going to ask? I agree with the reasoning.

**Comment by yvanlebras** [comment]
yes!

**Comment by Marie59** [comment]
should I create a new PR because this has too much conflicts ?

**Comment by sanjaysrikakulam** [comment]
> conflic

@bgruening merged with the latest branch changes. So, no more conflicts.

**Review by sanjaysrikakulam — APPROVED** [review]

**Pull request merged**
