### PR TITLE
add Metashark

### PR DESCRIPTION
**Pull request by bgruening**
ping @yvanlebras

### CODE REVIEW

**Comment by yvanlebras** [comment]
Amazing!!! 😍

**Comment by yvanlebras** [comment]
Hey Björn, it seems there is an issue, I think related to writing rights or something like this isn't it ?

`cp: cannot stat '/data/dnb03/galaxy_db/files/5/7/6/dataset_57684cc7-d915-49e1-9f90-a907c89bc14b.dat': No such file or directory`

**Comment by bgruening** [comment]
Yes, true. I went for the safe option. But as you said in chat, if you can not execute code we can be more relaxed here. Follow-up PR is coming.

**Comment by yvanlebras** [comment]
THANK YOU ! And sorry I don't see that this app was not on the good "tool_destination" earlier .....

**Pull request merged**
