### PR TITLE
change svg link

### PR DESCRIPTION
**Pull request by OlegZharkov**
A step towards AWS independence :sweat_smile:

### CODE REVIEW

**Comment by bgruening** [comment]
We can use AWS for the time being, but we should be prepared. Can we add this link as a comment?

**Comment by OlegZharkov** [comment]
> We can use AWS for the time being, but we should be prepared. Can we add this link as a comment?

should we do vice verca? add AWS link as a comment?

**Comment by bgruening** [comment]
As you like. I'm not sure if GitHub has any ratelimit. Or which one is faster.

**Comment by OlegZharkov** [comment]
> As you like. I'm not sure if GitHub has any ratelimit. Or which one is faster.

we can change it to https://galaxyproject.eu/. According to @hexylena we duplicate github content to our own websever.
But I guess, it would be hard compete with AWS. So I change it back to AWS and add a backup comment

**Comment by bgruening** [comment]
Thanks.

**Comment by OlegZharkov** [comment]
> Thanks.

thanks for the merge

**Pull request merged**
