### PR TITLE
add accept tag to upload files ?

### PR DESCRIPTION
**Pull request by MercierEva**
My user doesn't have the possibility of fetching data .. Is it the good way to resolve it ? 

Thanks,
Eva

### CODE REVIEW

**Comment by kysrpex** [comment]
@mira-miracoli On paper this looks good right?

**Comment by bgruening** [comment]
What are the symptoms @MercierEva ? I'm wondering why this was never needed before?

**Comment by MercierEva** [comment]
I wanted to upload a BAM file and the job failed with this error :
No destinations are available to fulfill request: User: eva.mercier@irisa.fr, Tool: __DATA_FETCH__, Rule: User: eva.mercier@irisa.fr, Tool: __DATA_FETCH__

Before the success of the fr-pulsar connection, I was running on another worker nodes of type vgcnbwc-worker-fetch-8343.novalocal despite the require tag. Maybe because like the require tag didn't work, the program estimated I wasn't set a tag ?

**Comment by mira-miracoli** [comment]
My idea of this problem as follows:
The `upload` tag is automatically added, when you run the upload tool, no matter which user you are, but since your user has the pulsar tags set as requirement and there is no destination that has the tags
```
- pulsar
- pulsar-fr
- upload
```
you upload jobs are not matched.
To solve this we would need to set the user tags only if the job does not contain the __DATA_FETCH__ tool.

**Comment by kysrpex** [comment]
> My idea of this problem as follows: The `upload` tag is automatically added, when you run the upload tool, no matter which user you are, but since your user has the pulsar tags set as requirement and there is no destination that has the tags
> 
> ```
> - pulsar
> - pulsar-fr
> - upload
> ```
> 
> you upload jobs are not matched. To solve this we would need to set the user tags only if the job does not contain the **DATA_FETCH** tool.

This is how I see it too. If we merged this PR, the upload job would be processed in France. I commented _"on paper this looks good"_, but actually I lack the knowledge to know if this is even possible.

**Comment by kysrpex** [comment]
> > My idea of this problem as follows: The `upload` tag is automatically added, when you run the upload tool, no matter which user you are, but since your user has the pulsar tags set as requirement and there is no destination that has the tags
> > ```
> > - pulsar
> > - pulsar-fr
> > - upload
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you upload jobs are not matched. To solve this we would need to set the user tags only if the job does not contain the **DATA_FETCH** tool.
> 
> This is how I see it too. If we merged this PR, the upload job would be processed in France. I commented _"on paper this looks good"_, but actually I lack the knowledge to know if this is even possible.

I just learned that it is not possible :sweat_smile: . Then indeed we need an exception for the data fetch tool.

**Comment by MercierEva** [comment]
Thanks for theses explanations

**Pull request closed without merging**
