### PR TITLE
CZ pulsar (for CESNET)

### PR DESCRIPTION
**Pull request by martindemko**
Adds TPV connection to testing cz pulsar (for CESNET) with access for one user (me, Martin Demko).

### CODE REVIEW

**Review by kysrpex — CHANGES_REQUESTED** [review]
Hi!

You also need to add a runner to [templates/galaxy/config/job_conf.yml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/be21746823e42434eab7a02c221e1615aa9886f7/templates/galaxy/config/job_conf.yml), like this.

**job_conf.yml**
```yaml
    - id: pulsar_eu_cz01
      load: galaxy.jobs.runners.pulsar:PulsarMQJobRunner
      params:
        amqp_url: "pyamqp://galaxy_cz01:{{ rabbitmq_password_galaxy_be01 }}@mq.galaxyproject.eu:5671//pulsar/galaxy_cz01?ssl=1"
        galaxy_url: "https://usegalaxy.eu"
        manager: production
        amqp_acknowledge: "true"
        amqp_ack_republish_time: 300
        amqp_consumer_timeout: 2.0
        amqp_publish_retry: "true"
        amqp_publish_retry_max_retries: 60
```

In addition, the rabbitmq user galaxy_cz01 needs to be created. You can do that by adding the following to [group_vars/mq.yml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/be21746823e42434eab7a02c221e1615aa9886f7/group_vars/mq.yml).

**mq.yml**
```yaml
  - user: galaxy_cz01
    password: "{{ rabbitmq_password_galaxy_cz01 }}"
    vhost: /pulsar/galaxy_cz01
```

The last piece of the puzzle is the password for the rabbitmq user, that should go to [secret_group_vars/pulsar.yml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/be21746823e42434eab7a02c221e1615aa9886f7/secret_group_vars/pulsar.yml). You **cannot** add this password yourself, as this file is encrypted with usegalaxu.eu's password. We'll generate a random secret and put it in the file for you.

**Comment by kysrpex** [comment]
That's absolutely true sorry, I was assuming this was a new setup. Then only the spacing needed to be taken care of :)

**Comment by bgruening** [comment]
@mtangaro maybe its a good time to update https://pulsar-network.readthedocs.io/en/latest/galaxy.html ? @martindemko could review it I guess :)

**Comment by bgruening** [comment]
Normally we run all the playbooks around midnight every day. So all changes will be available the day after. However, we can do exceptions and run it earlier as I just did. So check again in 30min and it should be available :)

**Comment by martindemko** [comment]
Thanks, man, I appreciate that.

**Pull request merged**
