### PR TITLE
Mount only Docker volumes required by Pulsar for tools running in `interactive_pulsar` and `embedded_pulsar_docker` (and their children)

### PR DESCRIPTION
**Pull request by kysrpex**
Closes usegalaxy-eu/issues#461.

@mira-miracoli Please pay special attention during the review since you know better about pulsar than me :) We will also **not** merge without your review.

### CODE REVIEW

**Comment by mira-miracoli** [comment]
I think the volumes should be fine. This affects embedded Pulsar only, so the jobs will not sent to remote Pulsar endpoints.
What I don't understand:

1. Why do we have the offline Tag still in place here, in the fist docker-embedded-pulsar destination?
2. Why do we have two identical destinations: `interactive_pulsar` and `embedded_pulsar_docker`

My guess: It was because we set the `GalaxyGroup == 'interactive''` in the first one and that was the difference.
Suggestion:
Keep only one of them.

**Comment by kysrpex** [comment]
1. I just did not sync my fork, nothing to worry about, only the [diff highlighted](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/864/files) gets merged.

grafik

**Comment by kysrpex** [comment]
2. After looking at both destinations for a while, I think this is just an artifact we have constructed because with just one destination we'd need something like this.

```yaml
single_destination:
    inherits: basic_docker_destination
    runner: pulsar_embedded
    max_accepted_cores: 24
    max_accepted_mem: 128
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
      docker_volumes: "$job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw,
        {{ cvmfs.data.path }}:{{ cvmfs.data.docker_perm }}"
    scheduling:
      accept:
        - docker
      require:
        - embedded-pulsar OR interactive
```

An immediate solution is the following.

```yaml
  embedded_pulsar_docker_abstract:
    inherits: basic_docker_destination
    abstract: true
    runner: pulsar_embedded
    max_accepted_cores: 24
    max_accepted_mem: 128
    min_accepted_gpus: 0
    max_accepted_gpus: 0
    params:
      docker_volumes: "$job_directory:rw,
        $tool_directory:ro,
        $job_directory/outputs:rw,
        $working_directory:rw,
        {{ cvmfs.data.path }}:{{ cvmfs.data.docker_perm }}"

  interactive_pulsar:
    inherits: embedded_pulsar_docker
    scheduling:
      accept:
        - docker
      require:
        - interactive
  
  embedded_pulsar_docker:
    inherits: embedded_pulsar_docker
    scheduling:
      require:
        - docker
        - embedded-pulsar
```

I think the whole thing boils down to we want to have an `interactive` tag in addition to `embedded-pulsar`. An alternative would be to have no destination with the `interactive` tag and add a rule to either the `default` tool or the `interactive_tool` that adds the embedded-pulsar tag to all interactive tools.

**Comment by kysrpex** [comment]
Let me know which solution do you prefer or whether you have extra different ideas.

**Comment by kysrpex** [comment]
It's true though, that `GalaxyGroup == "interactive"` in the `interactive_tool` is already making interactive tools go somewhere else, so ~~I guess we do not want to do this~~ does not apply so clearly.

**Comment by mira-miracoli** [comment]
Yes I fully agree with you. I think in this case it is better to keep the redundant destinations.

**Comment by kysrpex** [comment]
> Yes I fully agree with you. I think in this case it is better to keep the redundant destinations. Thank you for the clear explanation

I will nevertheless commit the abstract destination without scheduling tags before u approve.

**Comment by kysrpex** [comment]
It took a while because I wanted to make sure [inheritance works as expected for `min_accepted_gpus` and `max_accepted_gpus`](https://github.com/galaxyproject/total-perspective-vortex/blob/1f5b0a58292b0080af333a4afaea885b5e2f9efd/tpv/core/entities.py#L592-L603). I am done with my changes.

**Review by sanjaysrikakulam — APPROVED** [review]
Looks good! Thank you!

**Review by mira-miracoli — APPROVED** [review]
Looks good to me

**Pull request merged**
