### PR TITLE
divand: `--user 999` not needed anymore

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by kysrpex** [comment]
> @kysrpex do you know why this is failing?

What is failing? ITs? Divand? TPV dry-run?

**Comment by bgruening** [comment]
This PR here :)

**Comment by bgruening** [comment]
@kysrpex any idea why this PR is failing?

**Comment by kysrpex** [comment]
Can you give a bit of context? What does not work? Writing the outputs? Running the IT? Reading the datasets?

**Comment by bgruening** [comment]
This Pull request here, is failing in the dry-run ... not sure what else I can say :)

**Comment by kysrpex** [comment]
In [this message](https://github.com/usegalaxy-eu/infrastructure-playbook/pull/908#issuecomment-1724919799)

> What is failing? ITs? Divand? TPV dry-run?

I have asked if the TPV dry-run is faialing.

> not sure what else I can say :)

Next time just say: "TPV dry-run is failing" :)

---

[This rule](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/3886cd108bc58942bc3c647c19633152dc614548/files/galaxy/tpv/tool_defaults.yml#L45-L52) uses `helpers.tool_version_gte` but `tool.version` is `None` for the mock tool TPV uses for the dry-run.

Solution: move the rule under the [alphafold key in tools.yml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/3886cd108bc58942bc3c647c19633152dc614548/files/galaxy/tpv/tools.yml#L226) (then it fails only for alphafold), do not use Python's `all` or fix the issue in TPV.

**Comment by kysrpex** [comment]
#919 should fix it, we can merge it to master, merge master into this branch and then merge this branch.

**Comment by kysrpex** [comment]
[New error](https://github.com/usegalaxy-eu/infrastructure-playbook/actions/runs/6378942723/job/17310467771#step:21:51):

> galaxy.jobs.mapper.JobMappingException: Interactive tools require registration. Please log-in or register on https://usegalaxy.eu/login

Do we fix it or do we merge? Really, the TPV dry-run logic needs some attention (e.g. it should not fail when things are working as expected, just like in this case).

**Comment by bgruening** [comment]
Feel free to merge!

**Pull request merged**
