### PR TITLE
Deploy GAPARS for Yvan

### PR DESCRIPTION
**Pull request by erasche**
@yvanlebras developed a manner to interact with [Massively Multiplayer Online Science (MMOS)](http://mmos.ch/) through MMOS API and receive the URL of a bee picture that the user has to identify for the [GAPARS](http://gapars.mmos.ch/) project

This will let us do citizen science within Galaxy, providing a framework to show users classification tasks that they can do after their jobs run. Like phdcomics but less fun and more work, but science benefits :)

image

- [webhook](https://github.com/usegalaxy-eu/galaxy/pull/22)
- [I've written a python version we can deploy](https://github.com/yvanlebras/GAPARS_Galaxy/tree/python)
- Waiting on an update from @yvanlebras to make it work :)

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome! We know someone from the GAPARS project - we should inform them if this goes online :) Amazing, cool stuff ....

**Comment by erasche** [comment]
Ok, got the server component working this morning with help from @yvanlebras so going to deploy that. We can continue webhook discussion to get all the remaining questions worked out on that issue :)

**Comment by yvanlebras** [comment]
Wonder Helena on the place!!!

**Comment by erasche** [comment]
https://usegalaxy.eu/gapars-experiment/ it's live. @yvanlebras could you maybe answer some questions and confirm that you're receiving data? Just to make sure everything is working :)

**Comment by yvanlebras** [comment]
OUhaouhou, really nice! Too amazing to see it online. I am checking on the MMOS developer portal side, it seems that there is a (last ?) issue concerning receiving the data, I'm on it and come back to you ASAP!

**Comment by erasche** [comment]
I found the issue concerning receiving: I never call the "submit data" function! hah.

**Comment by erasche** [comment]
But definitely on my end, I'm not sending a correct classification submission. One sec.

**Comment by erasche** [comment]
@yvanlebras ok, can you test again?

**Comment by yvanlebras** [comment]
Youhouhou, it works perfectly!
A    M     A     Z     I     N      GGGGGGGGGGGGGGGGG

**Comment by yvanlebras** [comment]
I forgot to answer here, sorry... It works perfectly! Just a little fix I we can, as the circumstances numbers are very small, it 's probably in seconds, but it should be milliseconds. If that's possible to make it in milliseconds instead... I will try on the upcoming days

**Comment by erasche** [comment]
Oh, yes, I see it. Ok, fixed.

**Pull request merged**
