### PR TITLE
Add logrotate for atop

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**

### CODE REVIEW

**Review by mira-miracoli — COMMENTED** [review]
thank you

**Review by mira-miracoli — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @sanjaysrikakulam if you agree please create an issue or add this to vgcn as well.

**Comment by sanjaysrikakulam** [comment]
It's also baked into the latest VGCN images.

**Comment by bgruening** [comment]
Awesome!

**Pull request merged**
