### PR TITLE
Add extra ressources for assembly tools

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by gmauro** [comment]
I'm collecting some stats

**Comment by gmauro** [comment]
quast 165
  samples: 15834
  default: 4 GB
  75.percentile: 343 MB
  95.percentile: 4 GB
  highest value: 89 GB
  
flye 249
  samples: 4454
  default: 24 GB
  75.percentile: 13 GB
  95.percentile: 61 GB
  highest value: 115 GB
  
megahit 682
  samples: 3929
  default: 48 GB
  75.percentile: 18 GB
  95.percentile: 85 GB
  highest value: 140 GB
  lowest value: 106 MB
  
abyss 624
  samples: 1776
  default: 4 GB
  75.percentile: 8 GB
  95.percentile: 73 GB
  highest value: 113 GB

**Comment by gmauro** [comment]
@bebatut what do you think of these values?

**Comment by bebatut** [comment]
Looks good. Thanks for looking at the stats

**Comment by bebatut** [comment]
How long it takes for the changes to be on the server?

**Pull request merged**
