### PR TITLE
add dnb09 to object_store_conf.xml

### PR DESCRIPTION
**Pull request by mira-miracoli**
Do not merge yet, we should manually test if dnb09 is available before merging

### CODE REVIEW

**Review by sanjaysrikakulam — APPROVED** [review]

**Comment by sanjaysrikakulam** [comment]
A note: Also, the VGCN userdata should be updated, and the currently running instances should be updated using `pssh`.

**Comment by bgruening** [comment]
Is it possible / desirable to have a pdssh task that checks the consistency of the mounts and maybe mounts them 🤔

**Comment by sanjaysrikakulam** [comment]
> Is it possible / desirable to have a pdssh task that checks the consistency of the mounts and maybe mounts them 🤔

Maybe we can have a corn job or something on sn06 (the key to access the workers is available only on sn06) that periodically checks the worker nodes against the new mounts repository and if anything is missing it can mount them and update the autofs conf files.

**Comment by kysrpex** [comment]
> > Is it possible / desirable to have a pdssh task that checks the consistency of the mounts and maybe mounts them thinking
> 
> Maybe we can have a corn job or something on sn06 (the key to access the workers is available only on sn06) that periodically checks the worker nodes against the new mounts repository and if anything is missing it can mount them and update the autofs conf files.

Agree but I'd either go for Jenkins and Ansible or bake something that does the task into the workers.

**Comment by sanjaysrikakulam** [comment]
> > > Is it possible / desirable to have a pdssh task that checks the consistency of the mounts and maybe mounts them thinking
> > 
> > 
> > Maybe we can have a corn job or something on sn06 (the key to access the workers is available only on sn06) that periodically checks the worker nodes against the new mounts repository and if anything is missing it can mount them and update the autofs conf files.
> 
> Agree but I'd either go for Jenkins and Ansible or bake something that does the task into the workers.

Baking into the image is not an option because the VGCN images are used by others as well. I am fine with a Jenkins project.

**Comment by kysrpex** [comment]
> > > > Is it possible / desirable to have a pdssh task that checks the consistency of the mounts and maybe mounts them thinking
> > > 
> > > 
> > > Maybe we can have a corn job or something on sn06 (the key to access the workers is available only on sn06) that periodically checks the worker nodes against the new mounts repository and if anything is missing it can mount them and update the autofs conf files.
> > 
> > 
> > Agree but I'd either go for Jenkins and Ansible or bake something that does the task into the workers.
> 
> Baking into the image is not an option because the VGCN images are used by others as well. I am fine with a Jenkins project.

As far as I know [we already bake stuff into _"internal"_ images](https://github.com/usegalaxy-eu/vgcn/blob/dev/ansible-roles/internal.yml) that is not available to the public, so **it should be possible**.

But I also prefer a Jenkins project :rofl:

**Review by kysrpex — APPROVED** [review]

**Comment by sanjaysrikakulam** [comment]
`dnb09` was mounted on all workers using `pssh` (by adding the required config to the `/etc/auto.data`) and the mount was also verified. So merging this PR.

**Pull request merged**
