### PR TITLE
Use s3fs as type for "Genome Ark Test Instance" file source (s3 does not exist anymore in Galaxy 23.1)

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Nice thanks! Can not approve

**Comment by kysrpex** [comment]
> Nice thanks! Can not approve

Something is still wrong, I will merge it when it works.

**Review by kysrpex — APPROVED** [review]

**Comment by kysrpex** [comment]
I got the hints of what to do from [here](https://github.com/usegalaxy-eu/galaxy/blob/5eb4c7cd7c617568af31cc7320761106a6f3a5d3/lib/galaxy/config/sample/file_sources_conf.yml.sample#L72-L86).

**Comment by bgruening** [comment]
Oh, nice thanks

**Pull request merged**
