### PR TITLE
correct "graph_display_data" -> "graph/display_data" for ecology and …

### PR DESCRIPTION
**Pull request by yvanlebras**
…nanopore + add "species_abundance" for ecology

I hope that I don't make a mistake ;)
- correcting "graph_display_data" from ecology domains and also for nanopore one as it appears to me that "graph/display_data" is tha good manner to write.
- add "species_abundance" tool section and related tools for ecology domains as I forgot it :(

### CODE REVIEW

**Comment by bgruening** [comment]
> correcting "graph_display_data" from ecology domains and also for nanopore one as it appears to me that "graph/display_data" is tha good manner to write.

Why is that? The should be with underscores: https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/files/galaxy/config/tool_conf.xml#L332

**Comment by yvanlebras** [comment]
Hmmm, in this file, there was 2 manners to write this section, "graph_display_data" and "graph/display_data* depending on the domain we look at. As for Ecology I was writing  "graph_display_data", as for nanopore domain, and the corresponding section was not displayed, I was thinking that the " nanopore manner" to write this tool section was bad and the good one was "graph/display_data" as for others domains. Sorry if I'm wrong and/or unclear ;)

**Comment by bgruening** [comment]
I see a Graph and Display section in https://nanopore.usegalaxy.eu ... let's see if this is magically fixed tm.

**Comment by yvanlebras** [comment]
Yes I saw it but was thinking that maybe this was manually fixed... Let's see ;) magic everywhere ;(

**Pull request merged**
