### PR TITLE
activate Singularity container resolver

### PR DESCRIPTION
**Pull request by bgruening**
This will make simple tools work in Singularity on pulsar.

edit: not really true we also need: https://github.com/usegalaxy-eu/vgcn/issues/24 unless we use Bjoerns hacked instance.

### CODE REVIEW

**Comment by bgruening** [comment]
@erasche can we use symlinks from main to test files that don't need to be different?

**Comment by erasche** [comment]
Yep! I mostly didn't do that, in case we wanted to test different configs on test before promoting to main

**Comment by bgruening** [comment]
Ok, then we are fine with a config-shift over time and with every new Galaxy release we try to diff?

**Comment by bgruening** [comment]
This works very beautifully with https://github.com/galaxyproject/galaxy/pull/8533!

**Comment by bgruening** [comment]
Going to get this in on a Friday evening --- jeez.

**Comment by erasche** [comment]
oh good it works :sweat_smile:

**Comment by bgruening** [comment]
:)

**Comment by bgruening** [comment]
Augustus and Maker goes to Singularity location, just in case you are working an GAA stuff ;)

**Pull request merged**
