### PR TITLE
Fix of incorrectly used brackets (2.0)

### PR DESCRIPTION
**Pull request by martindemko**
I still didn't catch the bug. The last fix made the singularity command look like this:
... --env "_JAVA_OPTIONS="-Xmx3G -Djava.io.tmpdir=$SCRATCHDIR"" ...
Trouble is -D... part, which is supposed to be a part of the variable value. That's why all jobs crash now.
Hopefully, this could work, but if somebody sees a clear solution, I'm all ears ;)

Thanks

### CODE REVIEW

**Comment by bgruening** [comment]
You could try `singularity_env_CONTAINER_ENV_VAR: "CONTAINER_VAR_VALUE"` https://github.com/galaxyproject/galaxy/pull/16666/files

**Comment by martindemko** [comment]
I see. Didn't know about this. Or maybe I did, but I definitely forgot. Thanks

**Comment by martindemko** [comment]
I changed the code now, but don't know if still can be applied as part of this PR or if I must do another one

**Comment by martindemko** [comment]
I adjusted the code, so hopefully, it will apply as part of this PR. But still not sure how Galaxy will interpret the brackets.

**Comment by bgruening** [comment]
Should we try that? It can be worse isn't it?

I'm not sure you need the double quotes to be honest.

**Comment by martindemko** [comment]
Let's try it, if you don't mind. I have no other option.

**Comment by martindemko** [comment]
Thanks

**Comment by bgruening** [comment]
Deployed!

**Pull request merged**
