### PR TITLE
Microgalaxy uses codex

### PR DESCRIPTION
**Pull request by mira-miracoli**
closes: https://github.com/usegalaxy-eu/issues/issues/634

- [ ] @paulzierep please check that the assumed URL I used in the iframe is correct, before we merge this

### CODE REVIEW

**Comment by bebatut** [comment]
@mira-miracoli the URL is the correct one. 
Can we merge to get that lab deployed? Thanks a lot 😄

**Review by bgruening — APPROVED** [review]

**Comment by bebatut** [comment]
Thanks a lot!

**Comment by bebatut** [comment]
How long does the new interface take to be visible on microgalaxy.usegalaxy.eu ?

**Comment by mira-miracoli** [comment]
I can run the playbook now, it takes about 1h unfortunately

**Comment by mira-miracoli** [comment]
I think it works :)
https://microgalaxy.usegalaxy.eu/

**Comment by bebatut** [comment]
It works! Thanks a lot!!!

**Comment by paulzierep** [comment]
Great thanks a lot @mira-miracoli

**Pull request merged**
