### PR TITLE
defined influx service, d-s-n not available in firewalld

### PR DESCRIPTION
**Pull request by mira-miracoli**
Even though it is in /etc/services

### CODE REVIEW

**Review by sanjaysrikakulam — APPROVED** [review]
Looks fine. Here is an alternative,

```
    - name: Configure firewalld to open ports
      firewalld:
        port: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      with_items:
        - 8086/tcp
```

**Comment by mira-miracoli** [comment]
Yes I know the port argument, I wanted to use @sj213's role for this, because we might want to distinguish between multiple zones and e.g. remove that service from public once the ESG projects are done using it

**Comment by sanjaysrikakulam** [comment]
> Yes I know the port argument, I wanted to use @sj213's role for this, because we might want to distinguish between multiple zones and e.g. remove that service from public once the ESG projects are done using it

Cool!

**Comment by mira-miracoli** [comment]
But would make sense to expand the role to also accept ports in the future

**Pull request merged**
