### PR TITLE
Update TIaaS to latest version

### PR DESCRIPTION
**Pull request by hexylena**
We replaced uwsgi with gunicorn, and made a lot of improvements to the aesthetics.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
ping @mira-miracoli  - might be relevant for your traefik work.

**Comment by mira-miracoli** [comment]
Is the `tiias_nginx_routes` variable set somewhere, do we have to set it? I cant see it here

**Comment by hexylena** [comment]
`tiias_nginx_routes` is set in the latest version of the role.  We now ship the default routes, so folks don't have to configure it themselves.

**Comment by hexylena** [comment]
If for some reason you want to rewrite those routes for traefik, just add them to the role and we can ensure they stay updated :)

**Pull request merged**
