### PR TITLE
sn07: Allow sn07 to have access to tiaas db and allow galaxy user

### PR DESCRIPTION
**Pull request by sanjaysrikakulam**
Attach PR to https://github.com/usegalaxy-eu/issues/issues/352

### CODE REVIEW

**Comment by bgruening** [comment]
The change looks good, but this needs a bit of discussion at some point.

Do we want to deploy those auxiliary services also on both nodes? Or only on one? Do we know that those services, like TIaaS are using the globally shared database and no internal database hosted on the same node - because this would then deliver different content from different nodes?

**Comment by sj213** [comment]
The netmask should be `/32` rather than `/24`; with a netmask of `/24` this entry grants access to **all** hosts in the `10.5.68.0/24` network (the last byte of the address is *ignored* in this case).

**Comment by mira-miracoli** [comment]
The IP address is from sn07

**Comment by sanjaysrikakulam** [comment]
@sj213 Thank you! I will add new commits.

@bgruening I see, then certainly we should discuss this.

**Comment by sanjaysrikakulam** [comment]
**With the latest commit:**
1. Updated the netmask for sn07.
2. Since the` galaxy-readonly` user does not have enough permission to access the tables of `galaxy` database I have replaced the `galaxy-readonly` with the actual `galaxy` database user account in the `pg_hba.conf`.

**Comment by hexylena** [comment]
@mira-miracoli pinged me regarding

> Do we want to deploy those auxiliary services also on both nodes? Or only on one?

Personally I would deploy auxiliary services on both:
- less room for failure, if one fails *and* your proxy rules are smart enough, you can redirect further requests to the other, zero downtime.
- load makes more sense when balanced, you don't have one node with constantly higher load that you have to mentally consider "why is this node doing slightly worse"

> Do we know that those services, like TIaaS are using the globally shared database and no internal database hosted on the same node - because this would then deliver different content from different nodes?

TIaaS stores nothing locally, it only talks to the database. It's effectively "stateless" (excepting DB connections). If TIaaS is returning different content from different nodes, this can *only* happen because the deployments are out of sync (e.g. running different commits), which would be more of a deployment problem rather than a 'having two' problem.

Or deploy to a VM instead and get them off of the headnode. TIaaS *was* only on the headnode because of the old DB access rules.

**Comment by sanjaysrikakulam** [comment]
Thank you @hexylena for the clarification.

**Review by bgruening — APPROVED** [review]
Not relevant for this PR, but maybe you also want to have the read-only user accessing the DB from the second headnode. For example the stats usecase from the second headnode.

**Comment by sanjaysrikakulam** [comment]
@bgruening right! I will add it too and will merge it. Thank you!

**Comment by sanjaysrikakulam** [comment]
When installing galaxy while using the readonly user ansible fails at a task with the following error

image

**Pull request merged**
