### PR TITLE
Require registration to run interactive tools

### PR DESCRIPTION
**Pull request by kysrpex**
Let's see what solution we decide to apply. If we want to go with this here is the PR.

### CODE REVIEW

**Comment by sanjaysrikakulam** [comment]
I am in favor of this.

**Comment by bgruening** [comment]
+1

**Comment by kysrpex** [comment]
Just in case it was not obvious, +1 too.

**Review by mira-miracoli — APPROVED** [review]
Yes, should not be allowed anonymous

**Review by sanjaysrikakulam — APPROVED** [review]

**Pull request merged**
