### PR TITLE
Adding a pulsar node at Cyfronet

### PR DESCRIPTION
**Pull request by darnik22**

### CODE REVIEW

**Comment by mira-miracoli** [comment]
Hello,
could you please add your endpoint 
[here](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0cb10b41f5be666c7791aa8ecfe7a14ad03647e5/files/galaxy/config/user_preferences_extra_conf.yml#L50)
and
[here](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0cb10b41f5be666c7791aa8ecfe7a14ad03647e5/files/galaxy/tpv/destinations.yml.j2#L243)
I would then add a password and share it with you privately

**Comment by darnik22** [comment]
Hi,
Currently we were able to allocate a 4 core VM. I hope it is ok for the beginning. I made the suggested changes.

**Comment by mira-miracoli** [comment]
@darnik22 thank you :)
Can you contact me in matrix (I'm in the WP3 group, same profile pic)
Then I can share the password with you

**Comment by darnik22** [comment]
Hi,
Where should I place the password? I'm following these docs https://pulsar-network.readthedocs.io/en/latest/pulsar.html. I have the following error when making `make check` in pulsar-infrastructure-playbook:
```
darin@darlap:~/git/pulsar-infrastructure-playbook$ make check
ansible-galaxy install -p roles -r requirements.yml
- galaxyproject.pulsar is already installed, skipping.
ansible-playbook -C -i inventory main.yml

PLAY [pulsarservers] *********************************************************************************************************************************************************************************************************************************************************************
ERROR! Attempting to decrypt but no vault secrets found
Makefile:17: recipe for target 'check' failed
make: *** [check] Error 4
```

**Comment by mira-miracoli** [comment]
https://github.com/usegalaxy-eu/pulsar-deployment
Here you find the readme, which explaines how to deploy a pulsar endpoint.
https://github.com/usegalaxy-eu/pulsar-deployment#configuring-a-new-pulsar-endpoint

**Comment by darnik22** [comment]
What about the condor password? Should I generate it?

**Comment by mira-miracoli** [comment]
yes this a secret only the endpoint maintainers should know

**Comment by darnik22** [comment]
Is it ok to use the master image instead of the dev image? I tried with `vggp-v60-j340-e3937ea797ed-dev` but it does not boot - just goes into grub with some XFS inode errors on the console...

**Comment by mira-miracoli** [comment]
Hi, we are currently re-factoring our build and release process and will release new images soon.
For the moment this image from one year ago should work:
https://usegalaxy.eu/static/vgcn/vggp-v60-j225-1a1df01ec8f3-dev.raw

**Comment by darnik22** [comment]
I deployed the pulsar endpoint using https://github.com/usegalaxy-eu/pulsar-deployment. Terraform and ansible execution ended successfully. What next?

**Review by mira-miracoli — APPROVED** [review]

**Comment by mira-miracoli** [comment]
Cool! I will merge your PR and redeploy our RabbitMQ and Galaxy and then everyone should be able to select your endpoint under `preferences → manage information` on usegalaxy.eu

**Pull request merged**
