### PR TITLE
initial version of cz01 config

### PR DESCRIPTION
**Pull request by martenson**

### CODE REVIEW

**Comment by martenson** [comment]
once (and if) this is merged, how do I get `rabbitmq_password_galaxy_cz01` ? :)

**Comment by gmauro** [comment]
We need to agree a secure channel

**Comment by martenson** [comment]
Taking out of WIP, does it seem ok? Once the MQ is established, is there a way how to force some test jobs with `cz01` as destination?

**Comment by gmauro** [comment]
I will add CZ pulsar in the remote resources in the preferences menu. So you can test it when/how you want

**Comment by gmauro** [comment]
Super @martenson !
Tomorrow, we will check for smoke :D

**Pull request merged**
